Skola/Models/UcenikViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Skola.Models
{
    public class UcenikViewModel
    {
        public int UcenikId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Pol { get; set; }
        public string Jmbg { get; set; }
        public string Adresa { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DatumRodjenja { get; set; }
        public string ImeRoditelja { get; set; }
        public int BrojUDnevniku { get; set; }
        public string Drzavljanstvo { get; set; }
        public int Odjeljenje { get; set; }
        public string NazivOdjeljena { get; set; }
        public int? GradId { get; set; }
        public string Grad { get; set; }
        public string Drzava { get; set; }
    }
}

Skola/Controllers/OcjenaController.cs
using Skola.DbModels;
using Skola.HelperClass;
using Skola.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Skola.Controllers
{
    public class OcjenaController : Controller
    {

        // GET: Ocjena
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(int id)
        {
            using (var context = new SkolaContext())
            {
                OcjenaViewModel ocjena = new OcjenaViewModel();
                ocjena.UcenikId = id;

                ViewBag.Nastavnici = context.Nastavniks.Select(n => new SelectListItem()
                {
                    Text = n.Ime + " " + n.Prezime,
                    Value = "" + n.NastavnikId
                }).ToList();

                ViewBag.Predmeti = context.Predmets.Select(p => new SelectListItem()
                {
                    Text = p.Naziv,
                    Value = "" + p.PredmetId
                }).ToList();

                return View(ocjena);
            }
        }

        [HttpPost]
        public ActionResult Create(OcjenaViewModel ocjena)
        {
            using (var context = new SkolaContext())
            {

                context.Ocjenes.Add(new Ocjene()
                {
                    OcjenaId = ocjena.OcjenaId,
                    UcenikId = ocjena.UcenikId,
                    Datum = ocjena.Datum,
                    VrijednostOcjene = ocjena.Vrijednost,
                    TipOcjene = (int)ocjena.TipOcjene,
                    Predmet = ocjena.Predmet,
                    Nastavnik = ocjena.Nastavnik
                });

                context.SaveChanges();
            }

            return RedirectToAction("Details", "Ucenik", new { id = ocjena.UcenikId });
        }

        public ActionResult Edit(string id)
        {
            using (var context = new SkolaContext())
            {
                int ocjenaID = Convert.ToInt32(id);
                Ocjene ocjena = context.Ocjenes.Find(ocjenaID);
                OcjenaViewModel o = new OcjenaViewModel()
                {
                    OcjenaId = ocjena.OcjenaId,
                    UcenikId = ocjena.UcenikId,
                    Datum = ocjena.Datum,
                    Vrijednost = ocjena.VrijednostOcjene,
                    TipOcjene = (TipOcjene)ocjena.TipOcjene,
                    Predmet = ocjena.Predmet,
                    Nastavnik = ocjena.Nastavnik
                };

                ViewBag.Nastavnici = context.Nastavniks.Select(n => new SelectListItem()
                {
                    Text = n.Ime + " " + n.Prezime,
                    Value = "" + n.NastavnikId
                }).ToList();

                ViewBag.Predmeti = context.Predmets.Select(p => new SelectListItem()
                {
                    Text = p.Naziv,
                    Value = "" + p.PredmetId
                }).ToList();

                return View(o);
            }
        }

        [HttpPost]
        public ActionResult Edit(OcjenaViewModel ocjena)
        {
            using(var context = new SkolaContext())
            {
                Ocjene o = context.Ocjenes.Find(ocjena.OcjenaId);
                o.OcjenaId = ocjena.OcjenaId;
                o.UcenikId = ocjena.UcenikId;
                o.Datum = ocjena.Datum;
                o.VrijednostOcjene = ocjena.Vrijednost;
                o.TipOcjene = (int)ocjena.TipOcjene;
                o.Predmet = ocjena.Predmet;
                o.Nastavnik = ocjena.Nastavnik;
                context.SaveChanges();
            }

            return RedirectToAction("Details", "Ucenik", new { id = ocjena.UcenikId });
        }

        public ActionResult Delete(string id)
        {
            using (var context = new SkolaContext())
            {
                int ocjenaID = Convert.ToInt32(id);
                Ocjene ocjena = context.Ocjenes.Find(ocjenaID);
                OcjenaViewModel o = new OcjenaViewModel()
                {
                    OcjenaId = ocjena.OcjenaId,
                    UcenikId = ocjena.UcenikId,
                    Datum = ocjena.Datum,
                    Vrijednost = ocjena.VrijednostOcjene,
                    TipOcjene = (TipOcjene)ocjena.TipOcjene,
                    Predmet = ocjena.Predmet,
                    Nastavnik = ocjena.Nastavnik
                };
                return View(o);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            int ucenikID = 0;
            using (var context = new SkolaContext())
            {
                ucenikID = context.Ocjenes.Find(id).UcenikId;
                context.Ocjenes.Remove(context.Ocjenes.Find(id));
                context.SaveChanges();
                return RedirectToAction("Details", "Ucenik", new { id = ucenikID });
            }
        }

    }
}

Skola/Controllers/UcenikController.cs
using Skola.DbModels;
using Skola.HelperClass;
using Skola.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Skola.Controllers
{
    public class UcenikController : Controller
    {

        List<UcenikViewModel> Ucenici = new List<UcenikViewModel>();

        // GET: Ucenik
        public ActionResult Index()
        {
            using(var context = new SkolaContext())
            {
                var ucenici = context.Uceniks.Select(u => new UcenikViewModel()
                {
                    UcenikId = u.UcenikID,
                    Ime = u.Ime,
                    Prezime = u.Prezime,
                    Pol = u.Pol,
                    Jmbg = u.JMBG,
                    Adresa = u.Adresa,
                    DatumRodjenja = u.DatumRodjenja,
                    ImeRoditelja = u.ImeRoditelja,
                    BrojUDnevniku = u.BrojUDnevniku,
                    Drzavljanstvo = u.Drzavljanstvo,
                    Odjeljenje = u.OdjeljenjeId,
                    NazivOdjeljena = u.Odjeljenje.Naziv,
                    Grad = u.Grad.Naziv,
                    Drzava = u.Grad.Drzava.Naziv
                }).ToList();
                
                return View(ucenici);
            }
            
        }

        public ActionResult Create()
        {
            ViewBag.Pol = new List<String>{ "Musko", "Zensko"};

            using(var context = new SkolaContext())
            {
                ViewBag.Odjeljenja = context.Odjeljenjes.Select(o => new SelectListItem()
                {
                    Text = o.Naziv,
                    Value = "" + o.OdjeljenjeId
                }).ToList();

                ViewBag.Drzave = context.Drzavas.Select(d => new SelectListItem()
                {
                    Text = d.Naziv,
                    Value = "" + d.DrzavaID
                }).ToList();

                ViewBag.Drzave.Insert(0, new SelectListItem() { Text = "Izaberi drzavu", Value = "-1" });

            }
            return View();
        }

        public ActionResult VratiGradove(int drzavaID)
        {
            using (var context = new SkolaContext())
            {
                var rezultat = context.Grads.Where(g => g.DrzavaID == drzavaID).Select(g => new
                {
                    g.GradID,
                    g.Naziv
                }).ToList();

                return new JsonResult() { Data = rezultat, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        [HttpPost]
        public ActionResult Create(UcenikViewModel ucenik)
        {
            using(var context = new SkolaContext())
            {
                context.Uceniks.Add(new Ucenik() { UcenikID = ucenik.UcenikId, Ime = ucenik.Ime, Prezime = ucenik.Prezime, Pol = ucenik.Pol,
                                JMBG = ucenik.Jmbg, Adresa = ucenik.Adresa, DatumRodjenja = ucenik.DatumRodjenja, ImeRoditelja = ucenik.ImeRoditelja,
                                BrojUDnevniku = ucenik.BrojUDnevniku, Drzavljanstvo = ucenik.Drzavljanstvo, OdjeljenjeId = ucenik.Odjeljenje, GradID = ucenik.GradId});
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(string id)
        {
            int ucenikID = Convert.ToInt32(id);
            using (var context = new SkolaContext())
            {
                Ucenik ucenik = context.Uceniks.Where(u => u.UcenikID == ucenikID).FirstOrDefault();
                UcenikViewModel ucenikViewModel = new UcenikViewModel(){ UcenikId = ucenik.UcenikID, Ime = ucenik.Ime, Prezime = ucenik.Prezime, Pol = ucenik.Pol,
                    Jmbg = ucenik.JMBG, Adresa = ucenik.Adresa, DatumRodjenja = ucenik.DatumRodjenja, ImeRoditelja = ucenik.ImeRoditelja,
                                BrojUDnevniku = ucenik.BrojUDnevniku, Drzavljanstvo = ucenik.Drzavljanstvo, Odjeljenje = ucenik.OdjeljenjeId };

                ViewBag.Pol = new List<String> { "Musko", "Zensko" };

                ViewBag.Odjeljenja = context.Odjeljenjes.Select(o => new SelectListItem()
                {
                    Text = o.Naziv,
                    Value = "" + o.OdjeljenjeId
                }).ToList();

                ViewBag.Drzave = context.Drzavas.Select(d => new SelectListItem()
                {
                    Text = d.Naziv,
                    Value = "" + d.DrzavaID
                }).ToList();

                ViewBag.Drzave.Insert(0, new SelectListItem() { Text = "Izaberi drzavu", Value = "-1" });

                return View(ucenikViewModel);
            }
        }

        [HttpPost]
        public ActionResult Edit(UcenikViewModel ucenik)
        {

            using(var context = new SkolaContext())
            {
                Ucenik uc = context.Uceniks.Find(ucenik.UcenikId);

                uc.UcenikID = ucenik.UcenikId;
                uc.Ime = ucenik.Ime;
                uc.Prezime = ucenik.Prezime;
                uc.Pol = ucenik.Pol;
                uc.JMBG = ucenik.Jmbg;
                uc.Adresa = ucenik.Adresa;
                uc.DatumRodjenja = ucenik.DatumRodjenja;
                uc.ImeRoditelja = ucenik.ImeRoditelja;
                uc.BrojUDnevniku = ucenik.BrojUDnevniku;
                uc.Drzavljanstvo = ucenik.Drzavljanstvo;
                uc.OdjeljenjeId = ucenik.Odjeljenje;
                uc.GradID = ucenik.GradId;

                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id)
        {

            int ucenikID = Convert.ToInt32(id);

            using (var context = new SkolaContext())
            {
                Ucenik ucenik = context.Uceniks.Where(u => u.UcenikID == ucenikID).FirstOrDefault();
                UcenikViewModel ucenikViewModel = new UcenikViewModel()
                {
                    UcenikId = ucenik.UcenikID,
                    Ime = ucenik.Ime,
                    Prezime = ucenik.Prezime,
                    Pol = ucenik.Pol,
                    Jmbg = ucenik.JMBG,
                    Adresa = ucenik.Adresa,
                    DatumRodjenja = ucenik.DatumRodjenja,
                    ImeRoditelja = ucenik.ImeRoditelja,
                    BrojUDnevniku = ucenik.BrojUDnevniku,
                    Drzavljanstvo = ucenik.Drzavljanstvo,
                    Odjeljenje = ucenik.OdjeljenjeId
                };

                return View(ucenikViewModel);

            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (var context = new SkolaContext())
            {
                context.Uceniks.Remove(context.Uceniks.Find(id));
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Details(string id)
        {
            int ucenikID = Convert.ToInt32(id);
            using (var context = new SkolaContext())
            {
                Ucenik ucenik = context.Uceniks.Where(u => u.UcenikID == ucenikID).FirstOrDefault();
                UcenikViewModel ucenikViewModel = new UcenikViewModel()
                {
                    UcenikId = ucenik.UcenikID,
                    Ime = ucenik.Ime,
                    Prezime = ucenik.Prezime,
                    Pol = ucenik.Pol,
                    Jmbg = ucenik.JMBG,
                    Adresa = ucenik.Adresa,
                    DatumRodjenja = ucenik.DatumRodjenja,
                    ImeRoditelja = ucenik.ImeRoditelja,
                    BrojUDnevniku = ucenik.BrojUDnevniku,
                    Drzavljanstvo = ucenik.Drzavljanstvo,
                    Odjeljenje = ucenik.OdjeljenjeId,
                    NazivOdjeljena = ucenik.Odjeljenje.Naziv,
                    Grad = ucenik.Grad.Naziv,
                    Drzava = ucenik.Grad.Drzava.Naziv
                };

                ucenikViewModel.NazivOdjeljena = ucenik.Odjeljenje.Naziv;

                ViewBag.Ocjene = context.Ocjenes.Where(o => o.UcenikId == ucenikID).Select(o => new OcjenaViewModel()
                {
                    OcjenaId = o.OcjenaId,
                    UcenikId = o.UcenikId,
                    Datum = o.Datum,
                    Vrijednost = o.VrijednostOcjene,
                    TipOcjene = (TipOcjene)o.TipOcjene,
                    Predmet = o.Predmet,
                    Nastavnik = o.Nastavnik,
                    ImeNastavnika = o.Nastavnik1.Ime,
                    PrezimeNastavnika = o.Nastavnik1.Prezime,
                    NazivPredmeta = o.Predmet1.Naziv
                }).ToList();

                return View(ucenikViewModel);
            }

        }

    }
}

Skola/Views/Ucenik/Create.cshtml
@model Skola.Models.UcenikViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var Pols = ViewBag.Pol;
    var Odjeljenja = ViewBag.Odjeljenja;
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Ucenik", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UcenikViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Hidden("UcenikId")
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @foreach (var ite in Pols as List<String>)
                {
                    <label>@Html.RadioButton("Pol", @ite) @ite</label>
                    <br />
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Jmbg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Jmbg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Jmbg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Drzava", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Drzava", ViewBag.Drzave as List<SelectListItem>, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("GradId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradId", new List<SelectListItem> { new SelectListItem() { Text = "Izaberi grad", Value = "-1" } },
                                                         new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumRodjenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumRodjenja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumRodjenja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImeRoditelja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImeRoditelja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImeRoditelja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojUDnevniku, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojUDnevniku, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojUDnevniku, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Drzavljanstvo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Drzavljanstvo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Drzavljanstvo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Odjeljenje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Odjeljenje", Odjeljenja as List<SelectListItem>, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/App/vratiGradove.js"></script>
}

Skola/Views/Ucenik/Delete.cshtml
@model Skola.Models.UcenikViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    @using (Html.BeginForm("Delete", "Ucenik", new { id = Model.UcenikId}, FormMethod.Post))
    {
        <h4>UcenikViewModel</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UcenikId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UcenikId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Ime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Prezime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Prezime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Pol)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Pol)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Jmbg)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Jmbg)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Adresa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adresa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DatumRodjenja)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DatumRodjenja)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ImeRoditelja)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImeRoditelja)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BrojUDnevniku)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BrojUDnevniku)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Drzavljanstvo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Drzavljanstvo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Odjeljenje)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Odjeljenje)
            </dd>

        </dl>


        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Skola/Views/Ucenik/Details.cshtml
@model Skola.Models.UcenikViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>UcenikViewModel</h4>
    <hr />
    <div class="row">
        <div class="col-6">
            <dt>
                @Html.DisplayNameFor(model => model.UcenikId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UcenikId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Ime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Prezime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Prezime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Pol)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Pol)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Jmbg)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Jmbg)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Adresa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adresa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DatumRodjenja)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DatumRodjenja)
            </dd>

        </div>
        <div class="col-6">

            <dt>
                @Html.DisplayNameFor(model => model.ImeRoditelja)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ImeRoditelja)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BrojUDnevniku)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BrojUDnevniku)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Drzavljanstvo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Drzavljanstvo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NazivOdjeljena)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NazivOdjeljena)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Grad)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Grad)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Drzava)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Drzava)
            </dd>

        </div>
    </div>

    <div class="col-12">
        <p>
            @Html.ActionLink("Create new", "Create", "Ocjena", new { id = Model.UcenikId }, new { })
        </p>
        @Html.Partial("_OcjenaIndex", ViewBag.Ocjene as IEnumerable<Skola.Models.OcjenaViewModel>)
    </div>

    <div class="col-md-12">
        <br />
        <br />
        <p>
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>

</div>

Skola/Views/Ucenik/_OcjenaIndex.cshtml
@model IEnumerable<Skola.Models.OcjenaViewModel>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Datum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vrijednost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipOcjene)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImeNastavnika)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrezimeNastavnika)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NazivPredmeta)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @Html.HiddenFor(modelItem => item.UcenikId)
        <td>
            @Html.DisplayFor(modelItem => item.Datum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vrijednost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipOcjene)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImeNastavnika)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrezimeNastavnika)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NazivPredmeta)
        </td>
        @Html.HiddenFor(modelItem => item.Predmet)

        @Html.HiddenFor(modelItem => item.Nastavnik)
        <td>
            @Html.ActionLink("Edit", "Edit", "Ocjena", new { id = item.OcjenaId }, new { }) |
            @Html.ActionLink("Details", "Details", "Ocjena", new { id = item.OcjenaId }, new { }) |
            @Html.ActionLink("Delete", "Delete", "Ocjena", new { id = item.OcjenaId }, new { })
        </td>
    </tr>
}

</table>